// ****************************** Verilog Output *******************************
// Project: uPgmSM
// Engineer: Michael A. Morris 
// 
// File name: RTFIFO_uPgm.v
// 
// Description:
// 
// Microprogram SM Demonstration
//
//
// Dependencies:
// 
//   None.
//
// 
// Revision: 0001
// 
//   Sunday, December 02, 2012  8:44:50 PM  Written by mcp_nano.exe
// 
//   DO NOT MODIFY THIS FILE!
//   This file was generated by SMRT_tool.exe
// 
// *****************************************************************************

always @(*)
begin
  case(PC[13:0])
    14'h000 : IR = 14'b00010000000000;
    14'h001 : IR = 14'b00100100000000;
    14'h002 : IR = 14'b00111001000100;
    14'h003 : IR = 14'b10001100000000;
    14'h004 : IR = 14'b01011111110000;
    14'h005 : IR = 14'b10000011000000;
    14'h006 : IR = 14'b01111011100000;
    14'h007 : IR = 14'b10000010000000;
    14'h008 : IR = 14'b10000000000000;
    14'h009 : IR = 14'b10101111110000;
    14'h00A : IR = 14'b10111011100000;
    14'h00B : IR = 14'b10000011000000;
    14'h00C : IR = 14'b10000000000000;
    14'h00D : IR = 14'b10000000000000;
    14'h00E : IR = 14'b10000000000000;
//
    14'h00F : IR = 14'b10000000000000;
    default : IR = 14'b00000000000000;
  endcase
end
